apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-service
  labels:
    app: console
spec:
  selector:
    app: console
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Expose UI externally
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console-deployment
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: redpanda-console:latest
        ports:
          - containerPort: 8080
        env:
          # Use the Service name for communication
          - name: KAFKA_BROKERS
            value: "redpanda-service:29092"
          - name: KAFKA_SCHEMAREGISTRY_URLS
            value: "http://redpanda-service:8081"
          - name: REDPANDA_ADMINAPI_URLS
            value: "http://redpanda-service:9644"
          - name: KAFKA_READINESS_TOPIC
            value: "redpanda-readiness"
        # Ensure Redpanda Service is ready before starting the Console Pod
        readinessProbe:
          tcpSocket:
            port: 29092
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"