apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  labels:
    app: redpanda
spec:
  selector:
    app: redpanda
  ports:
    # Internal Kafka broker port (used by consumer/producer apps)
    - name: kafka-internal
      protocol: TCP
      port: 29092
      targetPort: 29092
    # Schema Registry
    - name: schema-registry
      protocol: TCP
      port: 8081
      targetPort: 8081
    # Admin API
    - name: admin-api
      protocol: TCP
      port: 9644
      targetPort: 9644
  type: ClusterIP # Internal only access

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-deployment
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: redpanda:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 29092
          - containerPort: 8081
          - containerPort: 9644
        command:
          - redpanda
          - start
          - --overprovisioned
        env:
          - name: RPK_BROKER_ID
            value: "0"
          - name: RPK_ADVERTISE_KAFKA_ADDR
            value: "redpanda-service:29092"
          - name: RPK_KAFKA_ADDR
            value: "PLAINTEXT://0.0.0.0:29092"
          - name: RPK_SCHEMA_REGISTRY_LISTENERS
            value: "http://0.0.0.0:8081"
          - name: RPK_ADMIN_LISTENERS
            value: "http://0.0.0.0:9644"
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"